### ISSUE TITLE
Unable to run the application locally

### ISSUE THREAD

**Issue by aaditkamat** [graph-quilt/graphql-gateway-java#7]
**Describe the bug**
I get this compilation error in the `RuntimeGraphBuilder.java` when I try to run the application locally:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/aaditkamat/Desktop/Projects/graphql-gateway-java/src/main/java/com/intuit/graphql/gateway/graphql/RuntimeGraphBuilder.java:[59,48] incompatible types: invalid method reference
    incompatible types: java.lang.Object cannot be converted to com.intuit.graphql.orchestrator.ServiceProvider
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

**To Reproduce**

Run `mvn clean install` to get this compilation error.

**Expected behavior**

I expected the application to run locally without any errors.

**Additional context**

**Comment by CNAChino** [comment]
Hi @aaditkamat.  I was able to complie this on Java 8 and Java 11.  Can you give more info how to reproduce this.  Like:
Operating System
Java Version
Maven Version
What command (s) did you ran.

**Comment by aaditkamat** [comment]
@CNAChino, yes it has to do with the operating system, I was using Java 17 to compile this. I'll close the issue. Thanks for responding!
