### ISSUE TITLE
AWS Configure command in README.md is missing required parameters

### ISSUE THREAD

**Issue by CNAChino** [graph-quilt/graphql-gateway-java#8]
**Describe the bug**

After running `aws configure`, running some aws CLI is not working.  

**To Reproduce**

1. remove ~/.aws/credentials
2. run `aws configure`
3. cd /Users/caureus/projects/graph-quilt/graphql-gateway-java/local_registry/dev/registrations/1.0.0/petstore.app
3. aws --endpoint-url=http://localhost:4572/ s3 cp . s3://topics/graphql-gateway-java/dev/registrations/1.0.0/petstore.app --recursive

**Expected behavior**

**Solution**

Update README.md to vaalid region and output format value  in `aws configure.`

**Comment by Lyrratic** [comment]
I'll take a stab at this!

**Comment by CNAChino** [comment]
assigned to you @Lyrratic Thanks for contributing!
